namespace Company.WebService.Models.MAINDB {
	/// <summary>
	/// This is a replacement class for the class generated by Entity Framework.  The Entity Framework doesn't generate the property KundenGruppeRabatt correctly
	/// </summary>
	public partial class KundenGruppe {
		public int PkkundenGruppeId { get; set; }
		public string KundenGruppeName { get; set; }
		public decimal? KundenGruppeRabatt { get; set; } // This field is imported by dotnet ef dbcontext scaffold as just decimal.  It needs to be decimal? (nullable).
		public bool KundenGruppeVersand { get; set; }
		public decimal KundenGruppePmulti { get; set; }
		public string Navshortcutdimension3 { get; set; }
	}
}
